# Generated by Django 4.0 on 2021-12-26 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('twitter_id', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('ptype', models.CharField(choices=[('ESTJ', 'ESTJ'), ('ESTP', 'ESTP'), ('ESFJ', 'ESFJ'), ('ESFP', 'ESFP'), ('ENTJ', 'ENTJ'), ('ENTP', 'ENTP'), ('ENFJ', 'ENFJ'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ'), ('ISTP', 'ISTP'), ('ISFJ', 'ISFJ'), ('ISFP', 'ISFP'), ('INTJ', 'INTJ'), ('INTP', 'INTP'), ('INFJ', 'INFJ'), ('INFP', 'INFP')], max_length=4)),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submits', to='Test.respondent')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ans', models.IntegerField(choices=[(1, '1'), (2, '2'), (0, 'not answered')], default=0)),
                ('question_num', models.IntegerField()),
                ('submit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Test.submit')),
            ],
        ),
    ]
