# Generated by Django 4.0 on 2021-12-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_alter_respondent_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='gender',
            field=models.IntegerField(choices=[(0, 'female'), (1, 'male')]),
        ),
    ]
