# Generated by Django 4.0 on 2022-02-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0004_alter_submit_ptype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('option1', models.CharField(max_length=512)),
                ('option2', models.CharField(max_length=512)),
                ('num', models.IntegerField()),
            ],
        ),
    ]
